#!/usr/bin/env php
<?php
/**
 * File run
 *
 * PHP version 5.3+
 *
 * @author    Philippe Gaultier <pgaultier@sweelix.net>
 * @copyright 2010-2014 Sweelix
 * @license   http://www.sweelix.net/license license
 * @version   XXX
 * @link      http://www.sweelix.net
 * @category  demo
 * @package   sweelix.demo
 */
/**
 * include composer autoloader
 */
include('vendor/autoload.php');

/**
 * The runner will search the command into the "app" namespace and run
 * it if everything goes well
 */
sweelix\command\Runner::getRunner(array('namespace' => 'app'))->run();
